[package]
name = "git-absorb"
version = "0.1.0"
authors = ["Arnau Siches <asiches@gmail.com>"]
description = "Git command to absorb and rebase changes into your branch"
keywords = ["git", "rebase", "absorb", "util"]
license = "MIT"
Repository = "https://github.com/arnau/git-absorb"

[dependencies]
docopt = "0.6.*"
rustc-serialize = "0.3"
git2 = "0.3.*"
time = "0.1.*"
